import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import { sha256 } from '@/lib/hash';
import { checkRateLimit } from '@/lib/redis';
import { nanoid } from 'nanoid';

const ALLOWED_TYPES = new Set(['text', 'sticky', 'image', 'link', 'stroke']);

const REDIS_CONFIGURED =
  !!process.env.UPSTASH_REDIS_REST_URL &&
  process.env.UPSTASH_REDIS_REST_URL !== 'https://placeholder.upstash.io';

const MAX_KEY_LENGTH = 500;
const MAX_HINT_LENGTH = 200;
// Board codes are 6 URL-safe chars (nanoid alphabet: A-Z0-9_-)
const BOARD_CODE_RE = /^[A-Z0-9_-]{6}$/;
// User IDs are 8 lowercase hex chars (generated by identity.ts)
const USER_ID_RE = /^[0-9a-f]{8}$/;
// Maximum safe coordinate magnitude (well beyond any real canvas use)
const COORD_LIMIT = 10_000_000;

function isValidUserId(uid: string | null): uid is string {
  return !!uid && USER_ID_RE.test(uid);
}

function isValidBoardCode(code: string): boolean {
  return BOARD_CODE_RE.test(code);
}

function isFiniteCoord(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value) && Math.abs(value) <= COORD_LIMIT;
}

/** Only allow http:// and https:// URLs to prevent javascript: / data: URI injection. */
function isValidHttpUrl(value: unknown): boolean {
  if (typeof value !== 'string') return false;
  try {
    const u = new URL(value);
    return u.protocol === 'https:' || u.protocol === 'http:';
  } catch {
    return false;
  }
}

/** Validate per-type element data. Returns an error string or null if valid. */
function validateData(type: string, data: unknown): string | null {
  if (!data || typeof data !== 'object' || Array.isArray(data)) return 'Invalid data';
  const d = data as Record<string, unknown>;

  if (type === 'text') {
    if (typeof d.text !== 'string' || d.text.length === 0 || d.text.length > 2000) return 'Text must be 1–2000 chars';
    if (d.fontSize !== undefined && (typeof d.fontSize !== 'number' || d.fontSize < 8 || d.fontSize > 200)) return 'Invalid fontSize';
  } else if (type === 'sticky') {
    if (typeof d.text !== 'string' || d.text.length > 2000) return 'Text must be ≤2000 chars';
  } else if (type === 'image') {
    if (!isValidHttpUrl(d.url)) return 'Image URL must be a valid http:// or https:// address';
    if (d.width !== undefined && (typeof d.width !== 'number' || d.width < 1 || d.width > 8000)) return 'Invalid width';
    if (d.height !== undefined && (typeof d.height !== 'number' || d.height < 1 || d.height > 8000)) return 'Invalid height';
  } else if (type === 'link') {
    if (!isValidHttpUrl(d.url)) return 'Link URL must be a valid http:// or https:// address';
    if (typeof d.label !== 'string' || d.label.length > 200) return 'Label must be ≤200 chars';
  } else if (type === 'stroke') {
    if (!Array.isArray(d.points) || d.points.length < 2 || d.points.length > 10_000) return 'Stroke must have 2–10000 points';
  }
  return null;
}

export async function GET(req: NextRequest) {
  const board = req.nextUrl.searchParams.get('board');
  if (!board || !isValidBoardCode(board)) return NextResponse.json({ error: 'Invalid board code' }, { status: 400 });
  // Exclude key_hash from the response to prevent offline brute-force attacks
  const { data, error } = await supabase
    .from('elements')
    .select('id, board_code, type, x, y, data, author_id, deleted, is_locked, key_hint')
    .eq('board_code', board)
    .eq('deleted', false);
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json(data ?? []);
}

export async function POST(req: NextRequest) {
  const userId = req.headers.get('X-User-Id');
  if (!isValidUserId(userId)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await req.json();
  const { board_code, type, x, y, data, key, key_hint } = body;

  if (!board_code || !isValidBoardCode(String(board_code))) {
    return NextResponse.json({ error: 'Invalid board code' }, { status: 400 });
  }
  if (!type || !ALLOWED_TYPES.has(String(type))) {
    return NextResponse.json({ error: 'Invalid element type' }, { status: 400 });
  }
  if (!isFiniteCoord(x) || !isFiniteCoord(y)) {
    return NextResponse.json({ error: 'Invalid coordinates' }, { status: 400 });
  }
  const dataErr = validateData(String(type), data);
  if (dataErr) return NextResponse.json({ error: dataErr }, { status: 400 });

  // Validate optional key fields
  let keyHash: string | null = null;
  let validatedKeyHint: string | null = null;
  let isLocked = false;

  if (key && typeof key === 'string' && key.length > 0) {
    if (key.length > MAX_KEY_LENGTH) return NextResponse.json({ error: 'Key too long' }, { status: 400 });
    keyHash = await sha256(key);
    isLocked = true;
  }
  if (key_hint && typeof key_hint === 'string' && key_hint.length > 0) {
    validatedKeyHint = key_hint.slice(0, MAX_HINT_LENGTH);
  }

  const id = nanoid();
  const { error } = await supabase.from('elements').insert({
    id,
    board_code: String(board_code),
    type: String(type),
    x,
    y,
    data,
    author_id: userId,
    deleted: false,
    key_hash: keyHash,
    key_hint: validatedKeyHint,
    is_locked: isLocked,
  });
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ id });
}

export async function PATCH(req: NextRequest) {
  const userId = req.headers.get('X-User-Id');
  if (!isValidUserId(userId)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const body = await req.json();
  const { id, ...updates } = body;
  if (!id || typeof id !== 'string') return NextResponse.json({ error: 'Missing element id' }, { status: 400 });

  // Fetch element for ownership / lock check
  const { data: existing, error: fetchErr } = await supabase
    .from('elements')
    .select('author_id, is_locked, key_hash')
    .eq('id', id)
    .single();

  if (fetchErr || !existing) return NextResponse.json({ error: 'Element not found' }, { status: 404 });

  if (existing.is_locked && existing.key_hash) {
    // Key-locked element: require correct key instead of author_id
    const providedKey = updates.key;
    if (!providedKey || typeof providedKey !== 'string') {
      return NextResponse.json({ error: 'Key required to modify this element' }, { status: 403 });
    }
    // Rate-limit failed attempts (requires Redis; silently skipped otherwise)
    if (REDIS_CONFIGURED) {
      try {
        const allowed = await checkRateLimit(`patch:${id}`, 5, 60);
        if (!allowed) {
          return NextResponse.json({ error: 'Too many attempts. Try again later.' }, { status: 429 });
        }
      } catch {
        // Redis unavailable at runtime – continue without rate limiting
      }
    }
    const inputHash = await sha256(providedKey);
    if (inputHash !== existing.key_hash) {
      return NextResponse.json({ error: 'Invalid key' }, { status: 403 });
    }
  } else {
    // Unlocked element: verify ownership via author_id
    if (existing.author_id !== userId) return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  // Only allow safe fields to be updated
  const allowed: Record<string, unknown> = {};
  if (typeof updates.deleted === 'boolean') allowed.deleted = updates.deleted;
  if (isFiniteCoord(updates.x)) allowed.x = updates.x;
  if (isFiniteCoord(updates.y)) allowed.y = updates.y;
  if (updates.data !== undefined) allowed.data = updates.data;

  // Lock management fields
  if (typeof updates.is_locked === 'boolean') {
    allowed.is_locked = updates.is_locked;
    if (!updates.is_locked) {
      // Removing the lock clears the key hash too
      allowed.key_hash = null;
      allowed.key_hint = null;
    }
  }
  if (updates.new_key && typeof updates.new_key === 'string' && updates.new_key.length > 0) {
    if (updates.new_key.length > MAX_KEY_LENGTH) return NextResponse.json({ error: 'Key too long' }, { status: 400 });
    allowed.key_hash = await sha256(updates.new_key);
    allowed.is_locked = true;
  }
  if (typeof updates.key_hint === 'string') {
    allowed.key_hint = updates.key_hint.length > 0 ? updates.key_hint.slice(0, MAX_HINT_LENGTH) : null;
  }

  if (Object.keys(allowed).length === 0) {
    return NextResponse.json({ error: 'No valid fields to update' }, { status: 400 });
  }

  const { error } = await supabase.from('elements').update(allowed).eq('id', id);
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ ok: true });
}
